ip prefix-list pl-downstream-network permit 10.200.0.0/24 ge 32
route-map rm-downstream-in permit 10
 match ip address prefix-list pl-downstream-network
exit

router bgp 64512
 bgp router-id 192.168.139.2
 bgp log-neighbor-changes
 neighbor downstream peer-group
 neighbor downstream remote-as 64513
 neighbor downstream timers 3 9
 bgp listen range 192.168.139.0/24 peer-group downstream

 address-family ipv4 unicast
  neighbor downstream route-map rm-downstream-in in
 exit-address-family
exit
