ip prefix-list svc-lb permit 10.200.0.0/24 ge 32
route-map worker-in permit 10
 match ip address prefix-list svc-lb
exit

router bgp 64512
 bgp router-id 192.168.139.2
 bgp log-neighbor-changes
 neighbor worker peer-group
 neighbor worker remote-as 64513
 neighbor worker timers 3 9
 bgp listen range 192.168.139.0/24 peer-group worker

 address-family ipv4 unicast
  neighbor worker route-map worker-in in
 exit-address-family
exit
