name: v31-xray

services:
  xray:
    image: ghcr.io/xtls/xray-core:26.3.27
    command: ["-config", "/etc/xray/config.json"]
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./config.json:/etc/xray/config.json:ro
