services:
  kube-xray:
    image: ghcr.io/xtls/xray-core:26.3.27
    container_name: kube-xray
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./config.json:/usr/local/etc/xray/config.json:ro
