/*
 * Copyright 2026-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.v31bank.bom;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

import org.gradle.testkit.runner.BuildResult;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * The one version pair nothing else checks: the protobuf the committed sources were
 * generated by, and the protobuf a consumer resolves.
 * <p>
 * protobuf refuses to load a message whose generated code is newer than the library
 * reading it, and it refuses at class initialisation — so the two disagreeing takes down
 * a service at context refresh, not at compile time, and only one that serves gRPC.
 *
 * @author Xander Wang
 * @since 0.2.0
 */
class ProtobufVersionIntegrationTests {

	/**
	 * How protoc records the version it generated by, spread over several lines and
	 * commented argument by argument.
	 */
	private static final Pattern GENCODE_VERSION = Pattern.compile("""
			validateProtobufGencodeVersion\\(.*?\
			major=\\s*\\*/\\s*(\\d+),.*?\
			minor=\\s*\\*/\\s*(\\d+),.*?\
			patch=\\s*\\*/\\s*(\\d+),""", Pattern.DOTALL);

	private static final String GENERATED_SOURCES = System.getProperty("generatedSources");

	@TempDir
	private Path consumer;

	/**
	 * Comparing the version stamped into the committed sources with the one a consumer
	 * resolves catches every way they can drift apart: a property moved without
	 * regenerating, a regeneration with a different protoc, or the platform's override
	 * dropped.
	 * @throws IOException if the generated sources cannot be read
	 */
	@Test
	void generatesForTheProtobufRuntimeAConsumerResolves() throws IOException {
		String gencode = gencodeVersion();
		BuildResult result = new ConsumerBuild(this.consumer).resolve(List.of("v31-ledger-api"));
		assertThat(result.getOutput())
			.as("generated code declares protobuf %s, so that is the runtime a consumer must get", gencode)
			.contains("protobuf-java-" + gencode + ".jar");
	}

	/**
	 * Read the version protoc stamped into what it wrote. It appears as the arguments of
	 * a {@code validateProtobufGencodeVersion} call, one per message class, all the same.
	 * @return the version the committed sources were generated by
	 * @throws IOException if the generated sources cannot be read
	 */
	private String gencodeVersion() throws IOException {
		try (Stream<Path> sources = Files.walk(Path.of(GENERATED_SOURCES))) {
			return sources.filter((file) -> file.toString().endsWith(".java"))
				.map(ProtobufVersionIntegrationTests::gencodeVersionIn)
				.flatMap(Optional::stream)
				.findFirst()
				.orElseThrow(() -> new AssertionError(
						"No generated source under " + GENERATED_SOURCES + " declares the protobuf version it "
								+ "was generated by, so what the runtime has to match is unknown."));
		}
	}

	private static Optional<String> gencodeVersionIn(Path source) {
		try {
			Matcher matcher = GENCODE_VERSION.matcher(Files.readString(source));
			return matcher.find() ? Optional.of(matcher.group(1) + "." + matcher.group(2) + "." + matcher.group(3))
					: Optional.empty();
		}
		catch (IOException ex) {
			throw new UncheckedIOException("Failed to read " + source, ex);
		}
	}

}
