// Copyright 2026-present the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package v31.ledger.v1;

import "google/protobuf/timestamp.proto";

option java_package = "org.v31bank.ledger.api.v1";

service LedgerAccountService {

  rpc CreateLedgerAccount(CreateLedgerAccountRequest) returns (CreateLedgerAccountResponse);

  rpc GetLedgerAccount(GetLedgerAccountRequest) returns (GetLedgerAccountResponse);

  rpc ListLedgerAccounts(ListLedgerAccountsRequest) returns (ListLedgerAccountsResponse);

  rpc UpdateLedgerAccount(UpdateLedgerAccountRequest) returns (UpdateLedgerAccountResponse);

  rpc DeleteLedgerAccount(DeleteLedgerAccountRequest) returns (DeleteLedgerAccountResponse);
}

enum LedgerAccountType {
  LEDGER_ACCOUNT_TYPE_UNSPECIFIED = 0;
  LEDGER_ACCOUNT_TYPE_ASSET = 1;
  LEDGER_ACCOUNT_TYPE_LIABILITY = 2;
  LEDGER_ACCOUNT_TYPE_EQUITY = 3;
  LEDGER_ACCOUNT_TYPE_REVENUE = 4;
  LEDGER_ACCOUNT_TYPE_EXPENSE = 5;
}

enum LedgerAccountStatus {
  LEDGER_ACCOUNT_STATUS_UNSPECIFIED = 0;
  LEDGER_ACCOUNT_STATUS_ACTIVE = 1;
  LEDGER_ACCOUNT_STATUS_CLOSED = 2;
}

message LedgerAccount {
  string id = 1;
  string code = 2;
  string name = 3;
  LedgerAccountType type = 4;
  LedgerAccountStatus status = 5;
  google.protobuf.Timestamp created_date = 6;
  google.protobuf.Timestamp last_modified_date = 7;
}

message CreateLedgerAccountRequest {
  string code = 1;
  string name = 2;
  LedgerAccountType type = 3;
}

message GetLedgerAccountRequest {
  string id = 1;
}

message CreateLedgerAccountResponse {
  LedgerAccount ledger_account = 1;
}

message GetLedgerAccountResponse {
  LedgerAccount ledger_account = 1;
}

message UpdateLedgerAccountResponse {
  LedgerAccount ledger_account = 1;
}

message DeleteLedgerAccountResponse {
  LedgerAccount ledger_account = 1;
}

message UpdateLedgerAccountRequest {
  string id = 1;
  string code = 2;
  string name = 3;
  LedgerAccountType type = 4;
  LedgerAccountStatus status = 5;
}

message DeleteLedgerAccountRequest {
  string id = 1;
}

message ListLedgerAccountsRequest {
  int32 page_number = 1;
  int32 page_size = 2;
  string code = 3;
  LedgerAccountType type = 4;
  LedgerAccountStatus status = 5;
}

message ListLedgerAccountsResponse {
  repeated LedgerAccount records = 1;
  int64 total = 2;
  int32 page_number = 3;
  int32 page_size = 4;
  int32 total_pages = 5;
  bool has_next = 6;
}
