[kube_control_plane]
control-plane1 ansible_host=control-plane1.orb.local
control-plane2 ansible_host=control-plane2.orb.local
control-plane3 ansible_host=control-plane3.orb.local

[etcd:children]
kube_control_plane

[kube_node]
worker1 ansible_host=worker1.orb.local
worker2 ansible_host=worker2.orb.local
worker3 ansible_host=worker3.orb.local

[all:vars]
ansible_user=wangxiang
