/*
 * Copyright 2026-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
	id "java-gradle-plugin"
	id "io.spring.javaformat" version "${javaFormatVersion}"
	id "checkstyle"
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(buildJavaVersion as int)
	}
}

tasks.withType(JavaCompile).configureEach {
	options.release = runtimeJavaVersion as int
}

checkstyle {
	toolVersion = "${checkstyleToolVersion}"
}

dependencies {
	checkstyle("com.puppycrawl.tools:checkstyle:${checkstyle.toolVersion}")
	checkstyle("io.spring.javaformat:spring-javaformat-checkstyle:${javaFormatVersion}")

	implementation(platform("org.springframework.boot:spring-boot-dependencies:$springBootVersion"))
	implementation("io.spring.javaformat:spring-javaformat-gradle-plugin:${javaFormatVersion}")
	implementation("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	implementation("tools.jackson.core:jackson-databind")

	testImplementation("org.assertj:assertj-core")
	testImplementation("org.junit.jupiter:junit-jupiter")
	testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

test {
	useJUnitPlatform()
}

gradlePlugin {
	plugins {
		bomPlugin {
			id = "org.v31bank.bom"
			implementationClass = "org.v31bank.build.bom.BomPlugin"
		}
		conventionsPlugin {
			id = "org.v31bank.conventions"
			implementationClass = "org.v31bank.build.ConventionsPlugin"
		}
		deployedPlugin {
			id = "org.v31bank.deployed"
			implementationClass = "org.v31bank.build.DeployedPlugin"
		}
		integrationTestPlugin {
			id = "org.v31bank.integration-test"
			implementationClass = "org.v31bank.build.test.IntegrationTestPlugin"
		}
		starterPlugin {
			id = "org.v31bank.starter"
			implementationClass = "org.v31bank.build.starters.StarterPlugin"
		}
		protobufPlugin {
			id = "org.v31bank.protobuf"
			implementationClass = "org.v31bank.build.ProtobufPlugin"
		}
		mavenRepositoryPlugin {
			id = "org.v31bank.maven-repository"
			implementationClass = "org.v31bank.build.MavenRepositoryPlugin"
		}
		optionalDependenciesPlugin {
			id = "org.v31bank.optional-dependencies"
			implementationClass = "org.v31bank.build.optional.OptionalDependenciesPlugin"
		}
		autoConfigurationPlugin {
			id = "org.v31bank.auto-configuration"
			implementationClass = "org.v31bank.build.autoconfigure.AutoConfigurationPlugin"
		}
		configurationPropertiesPlugin {
			id = "org.v31bank.configuration-properties"
			implementationClass = "org.v31bank.build.properties.ConfigurationPropertiesPlugin"
		}
		configurationMetadataPlugin {
			id = "org.v31bank.configuration-metadata"
			implementationClass = "org.v31bank.build.properties.ConfigurationMetadataPlugin"
		}
		flywayPlugin {
			id = "org.v31bank.flyway"
			implementationClass = "org.v31bank.build.FlywayPlugin"
		}
	}
}

