spring:
  application:
    name: v31-transfer-service
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: wangxiang
    password: ""
  flyway:
    schemas: transfer
    default-schema: transfer
    create-schemas: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: transfer
        format_sql: true
        highlight_sql: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 100

server:
  port: 8083

logging:
  level:
    org.v31bank: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.SQL_SLOW: INFO
    org.hibernate.orm.jdbc.bind: TRACE
